[package]
name = "grep-rust"
version = "0.1.0"
edition = "2021"
authors = ["NERVEbing <lc91926@gmail.com>"]
homepage = "https://lvlv.fun/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
